# 项目信息配置
project:
  env: eeas

# 服务器配置
server:
  port: 9000

# Spring配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    ## 默认日期格式化
    date-format: yyyy-MM-dd HH:mm:ss

# MyBatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml #对应mappers映射xml文件的所在路径
  configuration:
    map-underscore-to-camel-case: true # 使用resultType时自动将下划线转为驼峰命名

# 日志配置
logback:
  level: INFO
  appender: ${project.env}
